# PostgreSQL. Versions 8.2 and up are supported.
#
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: jon_overflow_development

  #username: jon_overflow
  #password:

test:
  <<: *default
  database: jon_overflow_test

production:
  <<: *default
  database: socal_kin_production
  username: socal_kin
  password: <%= ENV['SOCAL_KIN_DATABASE_PASSWORD'] %>
