default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  # host: deploy

development:
  <<: *default
  database: jon_overflow_development

test:
  <<: *default
  database: jon_overflow_test

production:
  <<: *default
  database: truenorth_production
  username: truenorth
  password: <%= ENV['TRUENORTH_DATABASE_PASSWORD'] %>
