default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost

development:
  <<: *default
  database: jon_overflow_development

  #username: jon_overflow
  #password:

test:
  <<: *default
  database: jon_overflow_test

production:
  <<: *default
  database: socal_kin_production
  username: socalkin
  password: <%= ENV['SOCALKIN_DATABASE_PASSWORD'] %>
